"use client";

import { useEffect, useRef, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import AuthStatus from "@/components/AuthStatus";
import StudyReferences from "@/components/StudyReferences";
import type { PubMedStudy } from "@/lib/pubmed";
import type { StudyContext, StudySimplification, StudyAssessment } from "@/lib/ai";
import PersonalNotes from "./PersonalNotes";

interface StudyDetailProps {
  study: PubMedStudy;
  source: "saved" | "live";
  /** UUID of the `studies` row from the DB (null when the study isn't saved). */
  studyId?: string | null;
  /** Previously-generated context loaded from the DB (null when none exists). */
  savedContext?: StudyContext | null;
  savedSourceInfo?: string | null;
  /** Previously-generated plain-English simplification (null when none exists). */
  savedSimplification?: StudySimplification | null;
  savedSimplificationSourceInfo?: string | null;
  /** Previously-generated qualitative evidence profile (null when none exists). */
  savedAssessment?: StudyAssessment | null;
  savedAssessmentSourceInfo?: string | null;
}

type ContextState = "idle" | "loading" | "done" | "error";

/**
 * StudyDetail - the core Explorer page.
 *
 * Product principle (per the project spec):
 *   1. The raw source (abstract/full text) is always shown first - the AI is
 *      an interpreter, never the source.
 *   2. Source facts, AI interpretation, and practical implications stay
 *      visually and structurally distinct.
 *   3. The AI-extracted breakdown is generated on demand, persisted to the
 *      regenerable `study_context` table, and re-loaded from the DB on
 *      revisit (DB-first; no AI call needed if it exists).
 *   4. Personal notes (Task 6) are user-owned and RLS-locked to the signed-in
 *      user; they need the study to be saved in the library first.
 */
export default function StudyDetail({
  study,
  source,
  studyId = null,
  savedContext = null,
  savedSourceInfo = null,
  savedSimplification = null,
  savedSimplificationSourceInfo = null,
  savedAssessment = null,
  savedAssessmentSourceInfo = null,
}: StudyDetailProps) {
  const router = useRouter();

  // Task 14: library save-state tracked client-side so the Save/Remove button
  // reflects reality immediately; `router.refresh()` then re-renders the server
  // page with the new `studyId` (unlocks PersonalNotes + StudyReferences).
  const [isSaved, setIsSaved] = useState(Boolean(studyId));
  const [saving, setSaving] = useState(false);
  const [removing, setRemoving] = useState(false);
  const [saveError, setSaveError] = useState<string | null>(null);
  const [librarySaveWarnings, setLibrarySaveWarnings] = useState<string[]>([]);

  // Study breakdown (AI extraction) state.
  // If a saved context exists in the DB we render it immediately (DB-first,
  // no AI call on revisit); otherwise it's auto-generated into React state on
  // mount (Task 14) and only persisted when the user clicks Save to Library.
  const [contextState, setContextState] = useState<ContextState>(
    savedContext ? "done" : "idle"
  );
  const [context, setContext] = useState<StudyContext | null>(savedContext);
  const [sourceInfo, setSourceInfo] = useState<string | null>(savedSourceInfo);
  const [contextError, setContextError] = useState<string | null>(null);

  // Plain-English simplification (Job 2) state — same pattern.
  const [simplificationState, setSimplificationState] = useState<ContextState>(
    savedSimplification ? "done" : "idle"
  );
  const [simplification, setSimplification] = useState<StudySimplification | null>(
    savedSimplification
  );
  const [simplificationSourceInfo, setSimplificationSourceInfo] = useState<
    string | null
  >(savedSimplificationSourceInfo);
  const [simplificationError, setSimplificationError] = useState<string | null>(
    null
  );

  // Qualitative evidence profile (Job 3 / Task 10) state — same pattern.
  const [assessmentState, setAssessmentState] = useState<ContextState>(
    savedAssessment ? "done" : "idle"
  );
  const [assessment, setAssessment] = useState<StudyAssessment | null>(
    savedAssessment
  );
  const [assessmentSourceInfo, setAssessmentSourceInfo] = useState<string | null>(
    savedAssessmentSourceInfo
  );
  const [assessmentError, setAssessmentError] = useState<string | null>(null);

  // Guard so React StrictMode's double-invoke in dev doesn't fire the
  // auto-generation twice.
  const autoGenerated = useRef(false);

  /**
   * Task 14: auto-generate into React state on load — no DB writes here.
   * Fetches each AI job ONLY if no saved copy was provided by the server.
   */
  useEffect(() => {
    if (autoGenerated.current) return;
    autoGenerated.current = true;

    if (!savedContext) void handleGenerateContext();
    if (!savedSimplification) void handleGenerateSimplification();
    if (!savedAssessment) void handleGenerateAssessment();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  /**
   * Generate the plain-English simplification (Job 2): call /api/simplify-study,
   * then persist the validated result into the regenerable study_simplifications
   * table (/api/save-simplification). Persistence failure is surfaced but does
   * NOT hide the freshly generated text.
   */
  const handleGenerateSimplification = async () => {
    setSimplificationState("loading");
    setSimplificationError(null);
    try {
      const res = await fetch("/api/simplify-study", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pmid: study.pmid }),
      });
      if (!res.ok) {
        const json = await res.json().catch(() => ({}));
        throw new Error(json.error ?? "Simplification failed");
      }
      const json = await res.json();
      setSimplification(json.simplification as StudySimplification);
      setSimplificationSourceInfo(json.sourceInfo as string);
      setSimplificationState("done");
    } catch (err) {
      setSimplificationState("error");
      setSimplificationError(
        err instanceof Error ? err.message : "Simplification failed"
      );
    }
  };

  /**
   * Generate the qualitative evidence profile (Job 3): call /api/assess-study,
   * then persist the validated result into the regenerable study_assessments
   * table (/api/save-assessment). Persistence failure is surfaced but does
   * NOT hide the freshly generated profile.
   */
  const handleGenerateAssessment = async () => {
    setAssessmentState("loading");
    setAssessmentError(null);
    try {
      const res = await fetch("/api/assess-study", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pmid: study.pmid }),
      });
      if (!res.ok) {
        const json = await res.json().catch(() => ({}));
        throw new Error(json.error ?? "Assessment failed");
      }
      const json = await res.json();
      setAssessment(json.assessment as StudyAssessment);
      setAssessmentSourceInfo(json.sourceInfo as string);
      setAssessmentState("done");
    } catch (err) {
      setAssessmentState("error");
      setAssessmentError(err instanceof Error ? err.message : "Assessment failed");
    }
  };

  const handleGenerateContext = async () => {
    setContextState("loading");
    setContextError(null);
    try {
      const res = await fetch("/api/extract-context", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ pmid: study.pmid }),
      });
      if (!res.ok) {
        const json = await res.json().catch(() => ({}));
        throw new Error(json.error ?? "Extraction failed");
      }
      const json = await res.json();
      setContext(json.context as StudyContext);
      setSourceInfo(json.sourceInfo as string);
      setContextState("done");
    } catch (err) {
      setContextState("error");
      setContextError(err instanceof Error ? err.message : "Extraction failed");
    }
  };

  /**
   * Task 14: persist ONE helper — POST a payload to a save endpoint and return
   * a human-readable failure message (or null on success). Individual AI save
   * failures must NOT fail the whole "Save to Library" action.
   */
  const persistAiState = async (
    url: string,
    body: unknown,
    label: string
  ): Promise<string | null> => {
    try {
      const res = await fetch(url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      if (!res.ok) {
        const json = await res.json().catch(() => ({}));
        return `${json.error ?? "Save failed"} (${label})`;
      }
      return null;
    } catch {
      return `Save failed (${label})`;
    }
  };

  /**
   * MANUAL SAVE ONLY (Task 14): saves the study, then persists any AI output
   * currently held in React state. This is the ONLY moment anything is written
   * to the database.
   */
  const handleSaveToLibrary = async () => {
    setSaving(true);
    setSaveError(null);
    setLibrarySaveWarnings([]);
    try {
      const res = await fetch("/api/save-study", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(study),
      });
      if (!res.ok) throw new Error("save failed");

      setIsSaved(true);
      // Re-render the server component so the new `studyId` propagates down
      // and PersonalNotes / StudyReferences unlock without a reload.
      router.refresh();

      const saveJobs: Promise<string | null>[] = [];
      if (contextState === "done" && context) {
        saveJobs.push(
          persistAiState(
            "/api/save-context",
            { study, context, sourceInfo },
            "study breakdown"
          )
        );
      }
      if (simplificationState === "done" && simplification) {
        saveJobs.push(
          persistAiState(
            "/api/save-simplification",
            { study, simplification, sourceInfo: simplificationSourceInfo },
            "plain-English explanation"
          )
        );
      }
      if (assessmentState === "done" && assessment) {
        saveJobs.push(
          persistAiState(
            "/api/save-assessment",
            { study, assessment, sourceInfo: assessmentSourceInfo },
            "evidence context"
          )
        );
      }
      const failures = (await Promise.all(saveJobs)).filter(
        (f): f is string => f !== null
      );
      if (failures.length > 0) {
        setLibrarySaveWarnings(failures);
      }
    } catch {
      setIsSaved(false);
      setSaveError("Failed to save. Please try again.");
    } finally {
      setSaving(false);
    }
  };

  /**
   * Task 14: remove the study from the shared library (DELETE route). The
   * React-state AI breakdowns stay visible — only the DB copy is removed.
   */
  const handleRemoveFromLibrary = async () => {
    setRemoving(true);
    setSaveError(null);
    setLibrarySaveWarnings([]);
    try {
      const res = await fetch(`/api/study/${study.pmid}`, {
        method: "DELETE",
      });
      if (!res.ok) throw new Error("remove failed");

      setIsSaved(false);
      router.refresh();
    } catch {
      setSaveError("Failed to remove the study. Please try again.");
    } finally {
      setRemoving(false);
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900">
      <div className="max-w-4xl mx-auto p-8">
        {/* Top bar */}
        <div className="flex flex-wrap items-center justify-between gap-3 mb-8">
          <Link href="/" className="text-sm font-medium text-blue-600 hover:text-blue-800">
            ← Back to search
          </Link>
          <div className="flex flex-wrap items-center gap-3">
            <span
              className={`text-xs font-semibold px-3 py-1 rounded-full ${
                source === "saved"
                  ? "bg-green-100 text-green-800"
                  : "bg-blue-100 text-blue-800"
              }`}
            >
              {source === "saved" ? "Saved in library" : "Fetched live from PubMed"}
            </span>
            <AuthStatus />
          </div>
        </div>

        {/* Header - the raw study facts */}
        <header className="mb-10">
          <h1 className="text-3xl font-bold leading-tight mb-3">{study.title}</h1>
          <div className="text-sm text-gray-600 space-y-1">
            <p>{study.authors}</p>
            <p className="italic">
              {study.journal}
              {study.publicationDate ? ` · ${study.publicationDate.slice(0, 4)}` : ""}
            </p>
            <p className="font-mono text-gray-500">PMID: {study.pmid}</p>
          </div>
        </header>

        {/* Actions */}
        <div className="flex flex-wrap gap-3 mb-10">
          <button
            onClick={isSaved ? handleRemoveFromLibrary : handleSaveToLibrary}
            disabled={saving || removing}
            className={
              isSaved
                ? "bg-red-600 text-white px-6 py-2.5 rounded-lg font-semibold hover:bg-red-700 disabled:opacity-50 transition-colors text-sm"
                : "bg-blue-600 text-white px-6 py-2.5 rounded-lg font-semibold hover:bg-blue-700 disabled:opacity-50 transition-colors text-sm"
            }
          >
            {saving
              ? "Saving..."
              : removing
                ? "Removing..."
                : isSaved
                  ? "Remove from Library"
                  : "Save to Library"}
          </button>
          <a
            href={`https://pubmed.ncbi.nlm.nih.gov/${study.pmid}/`}
            target="_blank"
            rel="noopener noreferrer"
            className="border border-gray-300 bg-white text-gray-700 px-6 py-2.5 rounded-lg font-semibold hover:bg-gray-100 transition-colors text-sm"
          >
            View original on PubMed ↗
          </a>
        </div>

        {saveError && (
          <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
            {saveError}
          </div>
        )}

        {librarySaveWarnings.length > 0 && (
          <div className="mb-8 p-3 rounded-lg bg-amber-50 border border-amber-200 text-amber-800 text-sm">
            Study saved, but some AI breakdowns could not be saved to the library:
            <ul className="list-disc ml-5 mt-1">
              {librarySaveWarnings.map((w, i) => (
                <li key={i}>{w}</li>
              ))}
            </ul>
          </div>
        )}

        {/* ============ RAW SOURCE ============ */}
        <section className="mb-10">
          <h2 className="text-lg font-bold mb-3 pb-2 border-b border-gray-200">
            What the study actually says
          </h2>
          <p className="text-gray-800 text-sm leading-relaxed whitespace-pre-line">
            {study.abstract}
          </p>
        </section>

        {/* ============ PLAIN-ENGLISH EXPLANATION (Job 2) ============ */}
        <section className="mb-10">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-4 pb-2 border-b border-gray-200">
            <h2 className="text-lg font-bold">In plain English</h2>
            <div className="flex items-center gap-3">
              {simplificationSourceInfo && (
                <SourceInfoBadge sourceInfo={simplificationSourceInfo} />
              )}
              <button
                onClick={handleGenerateSimplification}
                disabled={simplificationState === "loading"}
                className="bg-emerald-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-emerald-700 disabled:opacity-50 transition-colors text-sm"
              >
                {simplificationState === "loading"
                  ? "Explaining..."
                  : simplificationState === "done"
                    ? "Regenerate explanation"
                    : "Generate explanation"}
              </button>
            </div>
          </div>

          {simplificationState === "error" && (
            <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
              Failed to generate the explanation.
              {simplificationError ? ` ${simplificationError}` : ""}
            </div>
          )}


          {simplificationState === "loading" && (
            <div className="p-4 rounded-xl border border-gray-200 bg-white animate-pulse">
              <div className="h-3 w-40 bg-gray-200 rounded mb-3" />
              <div className="h-3 w-full bg-gray-100 rounded mb-1.5" />
              <div className="h-3 w-full bg-gray-100 rounded mb-1.5" />
              <div className="h-3 w-3/4 bg-gray-100 rounded" />
              <p className="text-sm text-gray-500 text-center pt-3">
                Re-explaining the study in plain English...
              </p>
            </div>
          )}

          {simplificationState === "done" && simplification ? (
            <div className="p-4 rounded-xl border border-emerald-200 bg-emerald-50">
              <p className="text-sm text-gray-800 leading-relaxed whitespace-pre-line">
                {simplification.simplified_text}
              </p>
            </div>
          ) : simplificationState === "idle" ? (
            <div className="p-4 rounded-xl border border-dashed border-gray-300 bg-white">
              <p className="text-sm text-gray-500">
                A plain-English explanation of this study for a curious lifter —
                what it tested, who was studied, and what the authors found —
                will appear here.
              </p>
            </div>
          ) : null}
        </section>

        {/* ============ STRUCTURED INTERPRETATION ============ */}
        <section className="mb-10">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-4 pb-2 border-b border-gray-200">
            <h2 className="text-lg font-bold">Study breakdown</h2>
            <div className="flex items-center gap-3">
              {sourceInfo && <SourceInfoBadge sourceInfo={sourceInfo} />}
              <button
                onClick={handleGenerateContext}
                disabled={contextState === "loading"}
                className="bg-indigo-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-indigo-700 disabled:opacity-50 transition-colors text-sm"
              >
                {contextState === "loading"
                  ? "Extracting..."
                  : contextState === "done"
                    ? "Regenerate context"
                    : "Generate context"}
              </button>
            </div>
          </div>

          {contextState === "error" && (
            <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
              Failed to generate the context.
              {contextError ? ` ${contextError}` : ""}
            </div>
          )}


          {contextState === "loading" && (
            <div className="space-y-4">
              {[0, 1, 2, 3].map((i) => (
                <div
                  key={i}
                  className="p-4 rounded-xl border border-gray-200 bg-white animate-pulse"
                >
                  <div className="h-3 w-32 bg-gray-200 rounded mb-3" />
                  <div className="h-3 w-full bg-gray-100 rounded mb-1.5" />
                  <div className="h-3 w-4/5 bg-gray-100 rounded" />
                </div>
              ))}
              <p className="text-sm text-gray-500 text-center pt-1">
                Reading the study and extracting structured information...
              </p>
            </div>
          )}

          {contextState === "done" && context ? (
            <div className="space-y-4">
              <BreakdownSection label="What question was the study asking?">
                <FieldRow label="Research question" value={context.research_question} />
              </BreakdownSection>

              <BreakdownSection label="Who was studied?">
                <div className="grid gap-2">
                  <FieldRow
                    label="Sample size"
                    value={context.sample_size !== null ? String(context.sample_size) : null}
                  />
                  <FieldRow label="Population" value={context.population} />
                  <FieldRow label="Training status" value={context.training_status} />
                </div>
              </BreakdownSection>

              <BreakdownSection label="How was it conducted?">
                <div className="grid gap-2">
                  <FieldRow label="Study design" value={context.study_design} />
                  <FieldRow label="Duration" value={context.duration} />
                  <FieldRow label="Intervention" value={context.intervention} />
                  <FieldRow label="Control" value={context.control} />
                </div>
              </BreakdownSection>

              <BreakdownSection label="What did they measure and find?">
                <div className="grid gap-2">
                  <FieldRow label="Outcomes measured" value={context.outcomes} />
                  <FieldRow label="Findings" value={context.findings} />
                </div>
              </BreakdownSection>

              <BreakdownSection label="Limitations stated by the paper">
                {context.limitations ? (
                  <p className="text-sm text-gray-800">{context.limitations}</p>
                ) : (
                  <p className="text-sm text-gray-400 italic">
                    None stated in the source.
                  </p>
                )}
              </BreakdownSection>

              {context.identified_limitations.length > 0 && (
                <div className="p-4 rounded-xl border border-gray-200 bg-white">
                  <h3 className="text-sm font-semibold text-gray-700 mb-3">
                    Identified limitations (AI-derived, each grounded in a stated fact)
                  </h3>
                  <div className="space-y-3">
                    {context.identified_limitations.map((item, i) => (
                      <div
                        key={i}
                        className="rounded-lg bg-amber-50 border border-amber-200 p-3"
                      >
                        <p className="text-sm text-gray-800">{item.limitation}</p>
                        <p className="text-xs text-amber-700 mt-1.5">
                          <span className="font-semibold">Based on:</span> "{item.based_on}"
                        </p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : contextState === "idle" ? (
            <div className="space-y-4">
              <BreakdownSection label="What question was the study asking?">
                AI extraction will appear here once generated.
              </BreakdownSection>
              <BreakdownSection label="Who was studied?">
                Population, sample size, and training status will appear here.
              </BreakdownSection>
              <BreakdownSection label="How was it conducted?">
                Study design, duration, intervention, and control conditions.
              </BreakdownSection>
              <BreakdownSection label="What did they measure and find?">
                Outcomes, measurements, and main findings.
              </BreakdownSection>
              <BreakdownSection label="Limitations">
                Paper-stated limitations and AI-identified limitations (with
                grounding quotes) will appear here.
              </BreakdownSection>
            </div>
          ) : null}
        </section>

        {/* ============ EVIDENCE CONTEXT (Job 3 / Task 10) ============ */}
        <section className="mb-10">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-4 pb-2 border-b border-gray-200">
            <h2 className="text-lg font-bold">Evidence context</h2>
            <div className="flex items-center gap-3">
              {assessmentSourceInfo && (
                <SourceInfoBadge sourceInfo={assessmentSourceInfo} />
              )}
              <button
                onClick={handleGenerateAssessment}
                disabled={assessmentState === "loading"}
                className="bg-teal-600 text-white px-4 py-2 rounded-lg font-semibold hover:bg-teal-700 disabled:opacity-50 transition-colors text-sm"
              >
                {assessmentState === "loading"
                  ? "Assessing..."
                  : assessmentState === "done"
                    ? "Regenerate assessment"
                    : "Generate assessment"}
              </button>
            </div>
          </div>

          {assessmentState === "error" && (
            <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
              Failed to generate the assessment.
              {assessmentError ? ` ${assessmentError}` : ""}
            </div>
          )}


          {assessmentState === "loading" && (
            <div className="space-y-3">
              {[0, 1, 2].map((i) => (
                <div
                  key={i}
                  className="p-4 rounded-xl border border-gray-200 bg-white animate-pulse"
                >
                  <div className="h-3 w-40 bg-gray-200 rounded mb-3" />
                  <div className="h-3 w-full bg-gray-100 rounded mb-1.5" />
                  <div className="h-3 w-4/5 bg-gray-100 rounded" />
                </div>
              ))}
              <p className="text-sm text-gray-500 text-center pt-1">
                Explaining why the study's design, sample, and measurements matter...
              </p>
            </div>
          )}

          {assessmentState === "done" && assessment ? (
            <div className="space-y-3">
              <AssessmentFactor
                label="Study design"
                value={assessment.design_context}
              />
              <AssessmentFactor
                label="Sample size"
                value={assessment.sample_size_context}
              />
              <AssessmentFactor
                label="Population"
                value={assessment.population_context}
              />
              <AssessmentFactor
                label="Training status"
                value={assessment.training_status_context}
              />
              <AssessmentFactor
                label="Duration"
                value={assessment.duration_context}
              />
              <AssessmentFactor
                label="Measurement"
                value={assessment.measurement_context}
              />
              <p className="text-xs text-gray-500 italic pt-1">
                No credibility score — these are the factors to weigh when
                judging how far this study can be applied.
              </p>
            </div>
          ) : assessmentState === "idle" ? (
            <div className="p-5 rounded-xl border border-dashed border-gray-300 bg-white">
              <p className="text-sm text-gray-500">
                This section will surface the factors that affect how broadly this
                study can be interpreted - sample size, study design, population,
                training status, duration, and measurement - with plain-language
                explanations of <em>why each factor matters</em>. No numerical
                "credibility score"; you'll get the context to judge for yourself.
              </p>
            </div>
          ) : null}
        </section>

        {/* ============ APPLICATION (Job 3 / Task 10) ============ */}
        <section className="mb-10">
          <div className="flex flex-wrap items-center justify-between gap-3 mb-4 pb-2 border-b border-gray-200">
            <h2 className="text-lg font-bold">What this might mean for training</h2>
            <div className="flex items-center gap-3">
              {assessmentState === "done" && (
                <span className="text-xs font-semibold px-3 py-1 rounded-full bg-amber-100 text-amber-800">
                  Interpretation — not established fact
                </span>
              )}
            </div>
          </div>

          {assessmentState === "error" && (
            <div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-red-700 text-sm">
              Failed to generate the training interpretation.
              {assessmentError ? ` ${assessmentError}` : ""}
            </div>
          )}

          {assessmentState === "done" && assessment ? (
            <div className="space-y-3">
              <div className="p-4 rounded-xl border border-amber-200 bg-amber-50">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">
                  If this generalises, it might suggest...
                </h3>
                {assessment.training_application ? (
                  <p className="text-sm text-gray-800 leading-relaxed">
                    {assessment.training_application}
                  </p>
                ) : (
                  <p className="text-sm text-gray-400 italic">
                    Not provided for this study.
                  </p>
                )}
              </div>
              <div className="p-4 rounded-xl border border-red-200 bg-red-50">
                <h3 className="text-sm font-semibold text-gray-700 mb-2">
                  What this does NOT mean
                </h3>
                {assessment.training_cautions ? (
                  <p className="text-sm text-gray-800 leading-relaxed whitespace-pre-line">
                    {assessment.training_cautions}
                  </p>
                ) : (
                  <p className="text-sm text-gray-400 italic">
                    Not provided for this study.
                  </p>
                )}
              </div>
              <p className="text-xs text-gray-500 italic">
                This is cautious interpretation by the AI, clearly separate from
                what the study actually states — use it to think, not as advice.
              </p>
            </div>
          ) : assessmentState === "idle" ? (
            <div className="p-5 rounded-xl border border-dashed border-gray-300 bg-white">
              <p className="text-sm text-gray-500">
                This section will translate the findings into practical training
                considerations - clearly labelled as <em>interpretation</em>, with
                explicit cautions about what this study does <em>not</em> establish.
              </p>
            </div>
          ) : null}
        </section>

        {/* ============ REFERENCES IN ARTICLES (Task 7) ============ */}
        <section className="mb-10">
          <h2 className="text-lg font-bold mb-4 pb-2 border-b border-gray-200">
            References in your articles
          </h2>
          {studyId ? (
            <StudyReferences studyId={studyId} />
          ) : (
            <div className="p-5 rounded-xl border border-dashed border-gray-300 bg-white">
              <p className="text-sm text-gray-500">
                Save this study to the library first — articles can only link
                claims to studies that are saved.
              </p>
            </div>
          )}
        </section>

        {/* ============ PERSONAL NOTES (Task 6) ============ */}
        <section>
          <h2 className="text-lg font-bold mb-4 pb-2 border-b border-gray-200">
            Personal notes
          </h2>
          <PersonalNotes studyId={studyId} pmid={study.pmid} />
        </section>
      </div>
    </div>
  );
}

/** Badge showing which source the AI actually read (full text / abstract). */
function SourceInfoBadge({ sourceInfo }: { sourceInfo: string }) {
  const label =
    sourceInfo === "full_text"
      ? "AI read: full text (PMC)"
      : sourceInfo === "abstract_only"
        ? "AI read: abstract only"
        : "AI read: provided text";
  return (
    <span className="text-xs font-semibold px-3 py-1 rounded-full bg-purple-100 text-purple-800">
      {label}
    </span>
  );
}

/** Label + value row for a single structured fact. */
function FieldRow({ label, value }: { label: string; value: string | number | null }) {
  return (
    <div className="flex flex-col gap-0.5">
      <span className="text-xs font-semibold uppercase tracking-wide text-gray-500">
        {label}
      </span>
      {value !== null && value !== "" ? (
        <span className="text-sm text-gray-800">{value}</span>
      ) : (
        <span className="text-sm text-gray-400 italic">Not stated in the source</span>
      )}
    </div>
  );
}

function BreakdownSection({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="p-4 rounded-xl border border-gray-200 bg-white">
      <h3 className="text-sm font-semibold text-gray-700 mb-2">{label}</h3>
      {children}
    </div>
  );
}

/** Evidence-context factor card: label + plain-language "why it matters". */
function AssessmentFactor({ label, value }: { label: string; value: string | null }) {
  return (
    <div className="p-4 rounded-xl border border-teal-100 bg-teal-50/50">
      <h3 className="text-xs font-semibold uppercase tracking-wide text-teal-800 mb-1.5">
        {label}
      </h3>
      {value ? (
        <p className="text-sm text-gray-800 leading-relaxed">{value}</p>
      ) : (
        <p className="text-sm text-gray-400 italic">Not provided.</p>
      )}
    </div>
  );
}
